CREATE UNDO TABLESPACE UNDOTBLSPC_1
  DATAFILE 'undotbs1_221.dbf' 
  SIZE 1024M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 2048M BLOCKSIZE 64K REUSE
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 32M
  RETENTION GAURANTEE
  ENCRYPTION USING 'RSA128';